heat_template_version: 2015-10-15

description: Define Neutron net and Server on this net

resources:

  my_net:
    type: OS::Neutron::Net

  server:
    type: OS::Nova::Server
    properties:
      image: cirros
      flavor: 'm1.nano'
      networks:
        - network: { get_resource: my_net }

