heat_template_version: queens

description: >
  Deploys server with user-provided image, key, flavor and config.
  Attaches to private Neutron network, and obtains floating IP on public network
  using a provided security group.
  Creates a volume of given size and attaches it to server.

parameters:
  key_name:
    type: string
    description: Keypair name
  image:
    type: string
    description: Image name
  flavor:
    type: string
    description: Flavor
  public_net:
    type: string
    description: Name or ID of the external network
  private_net:
    type: string
    description: Name or ID of the internal network
  private_subnet:
    type: string
    description: Subnet to get fixed IPs from
  security_group:
    type: string
    description: SecurityGroup assigned to the server
  config:
    type: string
    description: ID of the raw config resource to apply to servers
  pool:
    type: string
    description: ID of the Octavia loadbalanced Pool
  app_port:
    type: number
    description: Port the wepapp is running on

resources:

  server_port:
    type: OS::Neutron::Port
    properties:
      replacement_policy: AUTO
      network: { get_param: private_net }
      fixed_ips:
        - subnet: {get_param: private_subnet }
      security_groups:
        - get_param: security_group

  server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: server_port }

  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server_port }
      user_data_format: RAW
      user_data: { get_param: config }

  pool_member:
    type: OS::Octavia::PoolMember
    properties:
      pool: { get_param: pool }
      address: { get_attr: [server_port, fixed_ips, 0, ip_address] }
      protocol_port: { get_param: app_port }
      subnet: { get_param: private_subnet }


outputs:
  server_public_ip:
    description: Floating IP address of server on public network
    value:
      get_attr:
      - server_floating_ip
      - floating_ip_address
