heat_template_version: 2015-10-15

description: |
  Simplest web-app using netcat reporting only hostname.
  Specifically tailored for minimal Cirros image.
  Also creates a script to create/release CPU load on instances.
  Execute these commands on the instance via SSH:
  "cpuload" to load all CPU cores,
  "cpuload -r" to release the CPU load,
  "cpuload -s" to show status of CPU load (on/off),
  "cpuload -i" to identify the host by hostname.

parameters:

  app_port:
    type: number

  wc_curl_cli:
    type: string

resources:

  webapp_nc:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: |
            #! /bin/sh -v
            echo '$SCRIPT' > /bin/cpuload
            chmod 777 /bin/cpuload
            start-stop-daemon -S -bmp /var/run/simpleweb.pid -x nc -- -lk -p $PORT -e sh -c "echo -e \"HTTP/1.1 200 OK\r\nContent-Length: ${#body}\r\n\r\n${body}\""
            $wc_notify --data-binary '{"status": "SUCCESS"}'
          params:
            $SCRIPT: { get_file: "../../scripts/heat/cpuload" }
            $PORT: { get_param: app_port }
            $wc_notify: { get_param: wc_curl_cli }

outputs:
  OS::stack_id:
    value: { get_resource: webapp_nc }
