heat_template_version: 2015-10-15

description: |
  Simplest webapp using netcat (custom fit for CirrOS).

parameters:
  curl_cli:
    type: string
  port:
    type: number

resources:
  config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: |
            #! /bin/sh -v
            cat > /etc/init.d/simpleweb << EOF
            #Body=$(cat /etc/hostname)
            Body=$(hostname)
            Response="HTTP/1.1 200 OK\r\nContent-Length: ${#Body}\r\n\r\n$Body"
            while true; do
                echo -e ${Response} | nc -llp PORT
                #echo -e ${Response} | nc -l 0.0.0.0 PORT
            done
            EOF
            chmod +x /etc/init.d/simpleweb
            /etc/init.d/simpleweb start
            wc_notify --data-binary '{"status": "SUCCESS"}'
          params:
            wc_notify: { get_param: curl_cli }
            PORT: { get_param: port }

outputs:
  OS::stack_id:
    value: { get_resource: config }
