heat_template_version: 2015-10-15

description: |
  Simplest webapp using Python.

parameters:
  curl_cli:
    type: string
  port:
    type: number

resources:
  config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - echo  $(hostname) > index.html
          - str_replace:
              template: |
                #! /bin/bash -v
                python -m SimpleHTTPServer PORT &
                wc_notify --data-binary '{"status": "SUCCESS"}'
              params:
                PORT: { get_param: port }
                wc_notify: { get_param: curl_cli }
outputs:
  OS::stack_id:
    value: { get_resource: config }
