heat_template_version: 2015-04-30

parameters:
  count:
    type: number
    default: 1
  scalein:
    type: comma_delimited_list
    default: ""

resources:
  grp:
    type: OS::Heat::ResourceGroup
    properties:
      removal_policies: [ { resource_list: { get_param: scalein } } ]
      count: { get_param: count }
      resource_def:
        type: repro-nested.yaml
        properties:
          foo: bar
