heat_template_version: 2015-10-15

description: |
  AWS LB Template that assigns instances directly to AWS LB.

parameters:
  flavor:
   type: string
   default: m1.heat
  image:
    type: string
    default: fedora-heat-test-image
  AZ:
    type: string
    default: nova
  port:
    type: number
    default: 80

resources:

  ServerConfig:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - echo  $(hostname) > index.html
          - str_replace:
              template:
                python -m SimpleHTTPServer PORT &
              params:
                PORT: { get_param: port }

  ServerOne:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      user_data_format: RAW
      user_data: { get_resource: ServerConfig }

  ServerTwo:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      user_data_format: RAW
      user_data: { get_resource: ServerConfig }

  LoadBalancer:
    type: AWS::ElasticLoadBalancing::LoadBalancer
    properties:
      AvailabilityZones:
        - { get_param: AZ }
      Instances :
        - { get_resource: ServerOne }
        - { get_resource: ServerTwo }
      Listeners :
        - LoadBalancerPort : { get_param: port }
          InstancePort : { get_param: port }
          Protocol : HTTP

outputs:

  LB_ip:
    value: { get_attr: [LoadBalancer, DNSName]}
    description: LB ip address
