heat_template_version: 2015-10-15

description: 2 SoftwareConfig and SoftwareDeployment for update testing

resources:
  
  Server:
    type: OS::Nova::Server
    properties:
      image: cirros
      flavor: m1.nano

  SoftConfig1:
    type: OS::Heat::SoftwareConfig

  SoftConfig2:
    type: OS::Heat::SoftwareConfig

  SoftDeploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: { get_resource: SoftConfig2 }
      server: { get_resource: Server }
      signal_transport: NO_SIGNAL
