heat_template_version: 2015-10-15

description: Create native OS volume

parameters:
  size:
    type: number
    description: size of the volume
    default: 1

resources:
  volume:
    type: OS::Cinder::Volume
    #deletion_policy: Snapshot
    properties:
      size: { get_param: size }
