heat_template_version: 2015-10-15

description: Pool with pre-created Health monitor.

parameters:
  monitor:
    type: string
    description: id of the health monitor

resources:
  Pool:
    type: OS::Neutron::Pool
    properties:
      lb_method: ROUND_ROBIN
      protocol: TCP
      subnet: private
      vip:
        protocol_port: 22
      monitors:
      - { get_param: monitor }
